version: "3.9"
services:
  mysql:
    restart: always
    command: mysqld --sql_mode=""
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=admin

    networks:
      - services-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - services-network

  php-apache:
    image: php:apache
    container_name: "php-apache"
    ports:
      - 8089:80
    volumes:
      - ./php/src:/var/www/html/
      
    networks:
      - services-network

networks:
  services-network: